[platformio]
libdeps_dir = lib

[env:stm32_f407_jlink]
platform = ststm32
board = black_f407ve
framework = stm32cube
monitor_speed = 115200 

; Настройки программатора J-Link
upload_protocol = jlink
debug_tool = jlink

; Передаем J-Link команду на обязательную верификацию после прошивки
upload_flags =
    -CommandFile
    ${platformio.packages_dir}/tool-jlink/PlatformIO_Verify.jlink

; Перенаправляем стандартный Serial на аппаратный UART1 (пины PA9/PA10)
build_flags = 
	-D HSE_VALUE=8000000U