[platformio]
libdeps_dir = lib

[env:stm32_f407_jlink]
platform = ststm32
board = black_f407ve
framework = arduino
monitor_speed = 115200 
lib_deps = 
	nkawu/TFT 22 ILI9225@^1.4.5
	bogde/HX711@^0.7.5

; Настройки программатора J-Link
upload_protocol = jlink
debug_tool = jlink

; Передаем J-Link команду на обязательную верификацию после прошивки
upload_flags =
    -CommandFile
    ${platformio.packages_dir}/tool-jlink/PlatformIO_Verify.jlink

; Перенаправляем стандартный Serial на аппаратный UART1 (пины PA9/PA10)
build_flags = 
	-D ARDUINO_SERIAL_PORT=1