[platformio]
libdeps_dir = lib

[env:stm32_f030f4_jlink]
platform = ststm32
board = demo_f030f4
framework = stm32cube
monitor_speed = 115200 

; Setup J-Link
upload_protocol = jlink
debug_tool = jlink

; Firmware verify after upload
upload_flags =
    -CommandFile
    ${platformio.packages_dir}/tool-jlink/PlatformIO_Verify.jlink